### PR TITLE
Aziz

### PR DESCRIPTION
**Pull request by Azizozen92**

### CODE REVIEW

**Review by manasworks — APPROVED** [review]
Our side is Approve 👍

**Review by manasworks — CHANGES_REQUESTED** [review]
Need to change to POM, 🔢 
and it's optional you can use explicit wait now instead of regular sleep :)

**Review by manasworks — APPROVED** [review]

**Comment by AndrewSavinchuk** [comment]
Seen

**Comment by AndrewSavinchuk** [comment]
wow

**Review by AndrewSavinchuk — APPROVED** [review]
Nice job

**Pull request merged**
